threshold_positive: 4.7
threshold_negative: -4.7
target_time: '09:14:20'
order_execution_time: '09:15:01'
share_price_min_threshold: 50
share_price_max_threshold: 3000
stop_loss: 0.01
target1: 0.005
target2: 0.075
target3: 0.01
capital: 20000
buffer_entry: 0.001
buffer_trigger: 0.05
target1_quantity_pct: 0.7
target2_rem_quantity_pct: 0.5